#!/bin/bash
# updvcspkg

TMPDIR='/tmp/updvcspkg'

mkdir -p "$TMPDIR" &&
cd "$TMPDIR" || exit

checkpkgver() {
	git clone "https://aur.archlinux.org/$1.git"

	cd "$1" &&
	rm -f .toupd &&

	. PKGBUILD &&
	declare -F 'pkgver' &&

	makepkg -doc &&
	. PKGBUILD &&

	(( "$(vercmp "$pkgver-$pkgrel" "$2")" > 0 )) &&
	echo "$pkgver-$pkgrel" > .toupd
}

IFS=$'\n'; for pkg in $(pacman -Q | grep -- '-git'); do
	unset IFS
	checkpkgver $pkg &>/dev/null &
done; unset IFS; wait

for i in *; do
	[ -e "$i/.toupd" ] || continue

	if [ -t 0 ] || [ "$1" == '--color=always' ]; then
		echo -e "$(pacman -Q "$i" --color=always) -> \e[1;31m$(cat "$i/.toupd")\e[0m"
	else
		echo "$(pacman -Q "$i") -> $(cat "$i/.toupd")"
	fi
done

rm -rf "$TMPDIR"

# by Sdore, 2022
#  www.sdore.me
